### ISSUE TITLE
Get console url doesn't work

### ISSUE THREAD

**Issue by shadycuz** [adc4392/python-cloudatcost#11] opened 2017-03-30 23:49 UTC
But I couldn't get any of the commands to work from curl, but get_server_info() works fine.

```
>>> cac.get_console_url(xxxxx)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cacpy/CACPy.py", line 190, in get_console_url
    type="POST")
  File "/usr/local/lib/python2.7/dist-packages/cacpy/CACPy.py", line 59, in _make_request
    return ret.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by aculler** [comment] 2017-03-31 04:09
Hey @shadycuz! Thanks for the bug report and the interest.

I did some testing and I was definitely able to reproduce the issue. I get the same error when attempting to use the `get_console_url()` method and when I replicate the actual POST request it is making via curl, I get a blank response body. This is in contrast to when I make an incorrect curl request to that URL and get an actual error message.

This led me to think that maybe this is a CloudAtCost API issue. I popped over to their API's GitHub repo and found cloudatcost/api#48 which I believe references this exact issue. Unfortunately, the reporter of that bug wasn't exactly thorough in their reporting.

It's also important to note that the CAC support team may not actually monitor the GitHub issues page, since I believe that's mostly meant to document the API. You may have better luck by reporting it directly to them via their website. That said, as a budget VPS provider I don't know how responsive they'll be. I've only contacted them a few times (and it was a number of years ago) but they got back to me within a reasonable amount of time. 

Based on the number of other open and unacknowledged bugs in their GitHub repo, I'm not sure how well supported their API is.

Unfortunately what this all boils down to is that this bug exists independently of the API wrapper and as such I'll be closing it out. This is however a good case for #3 to add a better error message.

**Closed as completed by aculler** 2017-03-31 04:09 UTC
